api/GL/glcorearb.h, api/GL/glext.h, api/GLES2/gl2ext.h, extensions/NV/NV_draw_vulkan_image.txt, extensions/esext.php, extensions/glext.php, extensions/registry.py, xml/gl.xml
This extension has been public for over a year, but I just neglected to register it.
Here it is.
=> Register GL_NV_draw_vulkan_image extension

extensions/ARB/ARB_shader_ballot.txt
Fix copy/paste bug in issue 1 from merge request 36
=> Fix copy/paste bug in issue 1 from merge request 36

api/GLES2/gl2ext.h, extensions/MESA/MESA_shader_integer_functions.txt, xml/gl.xml
Fixes #3. @kaydenl please look this over. I screwed up the first PR attempt by basing it off a local copy of master that was actually ahead of github, so re-doing it.
=> Add ES support for MESA_shader_integer_functions (#3)

extensions/KHR/KHR_texture_compression_astc_hdr.txt, extensions/OES/OES_texture_compression_astc.txt
=> Updating ASTC extensions to remove incorrect restriction on mipmap size

extensions/ARB/ARB_sparse_texture.txt
Bugzilla: https://cvs.khronos.org/bugzilla/show_bug.cgi?id=13684
=> Add ARB_dsa interaction to GL_ARB_sparse_texture

extensions/ARB/ARB_parallel_shader_compile.txt
- fix long-standing typos
- better document the meaning of COMPLETION_STATUS
- add issue 3
Fixes: Gitlab WG-Docs 5
=> Revision 7 of ARB_parallel_shader_compile

extensions/EXT/EXT_shader_framebuffer_fetch.txt
=> Clarify interaction between EXT_shader_framebuffer_fetch and sRGB rendering

api/GL/glext.h, api/GL/glxext.h, api/GL/wglext.h, api/GLES/gl.h, api/GLES/glext.h, api/GLES2/gl2.h, api/GLES2/gl2ext.h, api/GLES3/gl3.h, extensions/ARB/ARB_create_context_no_error.txt, extensions/arbext.php, extensions/registry.py, xml/glx.xml, xml/wgl.xml
Hopefully everything is correct here.
=> Add {GLX,WGL}_ARB_create_context_no_error to the registry

xml/gl.xml
=> Change glGetShaderPrecisionFormat precision parameter len attribute to 1

api/GL/glext.h, api/GL/glxext.h, api/GL/wglext.h, api/GLES/gl.h, api/GLES/glext.h, api/GLES2/gl2.h, api/GLES2/gl2ext.h, api/GLES3/gl3.h, xml/gl.xml
=> Add NV_pixel_buffer_object to gl.xml

extensions/ARB/ARB_gl_spirv.txt
=> Fix for issue #90.

api/GL/glext.h, api/GL/glxext.h, api/GL/wglext.h, api/GLES/gl.h, api/GLES/glext.h, api/GLES2/gl2.h, api/GLES2/gl2ext.h, api/GLES3/gl3.h, extensions/NV/NV_query_resource.txt, extensions/NV/NV_query_resource_tag.txt, extensions/glext.php, extensions/registry.py, xml/gl.xml
New Nvidia video memory usage query extension at the object level (retry with unused files deleted).
=> new NV memory usage query extension

extensions/MESA/MESA_window_pos.txt
This pulls in the changes from Nicolas Kaiser (@nikai3d)  in Mesa commit
https://cgit.freedesktop.org/mesa/mesa/commit/?id=ae5776c41f12515bb73c07ee2a0aed56cdd1a1ef
=> MESA_window_pos: fix a couple typos

extensions/QCOM/QCOM_texture_foveated.txt
-Change status to complete
-Remove depth/stencil language relating to
discards and invalidates
=> Minor updates to QCOM_texture_foveated

extensions/AMD/AMD_gpu_shader_int16.txt, extensions/AMD/AMD_shader_ballot.txt
Add 16-bit integer type support in these specs.
=> Update the spec of AMD_shader_ballot and AMD_gpu_shader_int16

extensions/EXT/EXT_YUV_target.txt, extensions/OES/OES_EGL_image_external.txt
- OES_EGL_image_external.txt
- EXT_YUV_target.txt
=> Fix typo in extensions.

extensions/ARB/ARB_direct_state_access.txt
Fixes KhronosGroup/OpenGL-API#39.
=> ARB_direct_state_access: fix typos

extensions/EXT/EXT_external_objects.txt
Pointed out by Rodrigo Locatti (Thanks!)
=> Fixed external_objects typo: NamedBufferStroage

extensions/AMD/AMD_framebuffer_multisample_advanced.txt, extensions/esext.php, extensions/glext.php, extensions/registry.py, xml/gl.xml
Hi,
This is a new extension that we'd like to publish. Please review.
Thanks,
Marek
=> Add AMD_framebuffer_multisample_advanced

api/GL/wglext.h, xml/wgl.xml
=> Fix WGL_COLORSPACE_EXT

api/GL/wgl.h, xml/Makefile
=> Add target wgl.h

xml/gl.xml
fix https://github.com/KhronosGroup/OpenGL-Registry/issues/220
=> Missing enums

api/GL/glcorearb.h, api/GL/glext.h, api/GL/glxext.h, api/GL/wgl.h, api/GL/wglext.h, api/GLES/gl.h, api/GLES/glext.h, api/GLES2/gl2.h, api/GLES2/gl2ext.h, api/GLES3/gl3.h, extensions/EXT/EXT_texture_sRGB_R8.txt, extensions/esext.php, extensions/glext.php, extensions/registry.py, xml/gl.xml
=> Register EXT_texture_sRGB_R8 for GL

README.adoc
- "definining" -> "defining"
- "added and to the following sentence" -> "propose a pull request against the OpenGL-Registry
repository and adding the appropriate extension specifications"
- "if you find problems" -> "if you find any problems"
=> Fix errors in README.adoc

xml/genheaders.py
Signed-off-by: Adrian Negreanu <groleo@gmail.com>
=> genheaders.py: make it usable as module

extensions/NV/NV_scissor_exclusive.txt, extensions/esext.php, extensions/registry.py, xml/gl.xml
Adds ES extension number.
Adds NV_viewport_array and OES_viewport_array interactions for MAX_VIEWPORTS and GetFloati_v.
=> Adds ES support to NV_scissor_exclusive

api/GL/glext.h, api/GL/glxext.h, api/GL/wgl.h, api/GL/wglext.h, api/GLES/gl.h, api/GLES/glext.h, api/GLES2/gl2.h, api/GLES2/gl2ext.h, api/GLES3/gl3.h, extensions/EXT/EXT_depth_clamp.txt, extensions/EXT/EXT_texture_query_lod.txt, extensions/esext.php, xml/gl.xml
Also add XML entry for EXT_texture_query_lod
and mark EXT_texture_query_lod and EXT_depth_clamp as complete.
cc @gerddie
=> Update registry and headers

xml/glxproto.reserved.txt
=> glxproto: Document more GLX enumerateds

extensions/NV/NV_mesh_shader.txt, extensions/NV/NV_representative_fragment_test.txt, extensions/NV/NV_shader_texture_footprint.txt, extensions/esext.php, extensions/registry.py, xml/gl.xml
- NV_mesh_shader
- NV_shader_texture_footprint
- NV_representative_fragment_test
=> Adds ES support to some NV extensions

xml/gl.xml
Issue: #109 
Work Tracker: Perksey#1
This is the first PR regarding this issue. Subsequent PRs will follow.
=> Add missing enum groups

xml/gl.xml, xml/glx.xml, xml/wgl.xml
Just updates the year in the XML headers because my OCD eye noticed it.
=> Update copyright headers

extensions/ARB/ARB_gl_spirv.txt
Closes internal API issue 111.
=> Prevent user interface variables from containing a value of type OpTypeBool

extensions/ARB/ARB_texture_multisample.txt, extensions/ARB/ARB_texture_stencil8.txt, extensions/EXT/EXT_shader_image_load_store.txt, extensions/NV/NV_explicit_multisample.txt, extensions/NV/NV_texture_multisample.txt
Name string should start with `GL_`.
=> Correct name strings

xml/gl.xml
=> Fix invalid enum references in groupings (fixes #327)

xml/gl.xml
add some missing enums
fix references to enums that don't exist
merge some groups
=> fix some group definitions in gl.xml

extensions/APPLE/APPLE_float_pixels.txt, extensions/APPLE/APPLE_ycbcr_422.txt, extensions/EXT/EXT_frag_depth.txt, extensions/EXT/EXT_texture_array.txt, extensions/NVX/NVX_progress_fence.txt
=> Avoid cp1252 and mac-roman codepages

xml/gl.xml
Does what it says on the tin.
- Fix #355
- Fix #356
- Fix #357
- Fix #358
- Add groups to grouped blocks, fixes #359
=> Group fixes.

extensions/ARB/ARB_shader_storage_buffer_object.txt
Fixed typo in MAX_COMBINED_SHADER_OUTPUT_RESOURCES listing inside ARB_shader_storage_buffer_object opengl extension
=> PR for https://github.com/KhronosGroup/OpenGL-Registry/issues/386

extensions/EXT/GLX_EXT_no_config_context.txt, extensions/glext.php, extensions/registry.py
This didn't get added to the registry generation script, oops.
=> Add GLX_EXT_no_config_context to the registry

extensions/EXT/EXT_texture_sRGB_RG8.txt, extensions/registry.py, xml/gl.xml
Closes #450
Related: https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/8060
=> Register & add interactions for EXT_texture_sRGB_RG8

api/GL/glcorearb.h, api/GL/glext.h, api/GLES2/gl2.h, api/GLES2/gl2ext.h, extensions/NV/NV_path_rendering.txt, xml/gl.xml
=> Fix non-standard array declaration in XML

extensions/QCOM/QCOM_render_shared_exponent.txt, extensions/esext.php, extensions/registry.py, xml/gl.xml
Allows rendering to GL_RGB9_E5
=> Add QCOM_render_shared_exponent

extensions/NV/NV_read_depth_stencil.txt
Per #488
@dgkoch please approve if it seems OK to you.
=> Remove references to nonexistent extension

extensions/NV/NV_gpu_program5.txt, extensions/NV/NV_shader_buffer_store.txt
=> Update extension specifications for MemoryBarrierNV in NV_gpu_program5 and NV_shader_buffer_store

xml/gl.xml
These are some enum fixes that I found while making #534.
=> Enum fixes found while making #534

api/GL/glext.h, api/GL/glxext.h, api/GL/wgl.h, api/GL/wglext.h, api/GLES/gl.h, api/GLES/glext.h, api/GLES2/gl2.h, api/GLES2/gl2ext.h, api/GLES3/gl3.h, api/GLSC2/glsc2.h, api/GLSC2/glsc2ext.h, extensions/EXT/EXT_framebuffer_blit_layers.txt, extensions/glext.php, extensions/registry.py, xml/gl.xml
Closes https://github.com/KhronosGroup/OpenGL-Registry/issues/532
Mesa implementation https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/18847
=> Add GL_EXT_framebuffer_blit_layers

api/GL/glcorearb.h, api/GL/glext.h, api/GLES2/gl2ext.h, xml/gl.xml
=> Add missing glNamedFramebufferTextureMultiviewOVR to XML / headers

extensions/NV/NV_polygon_mode.txt
Issue [#187](https://gitlab.khronos.org/opengl/API/-/issues/187) - Correct parameter name and add Enable/Disable to list of functions for New Tokens.
=> Clarify NV_polygon_mode extended entrypoints

extensions/ARM/ARM_shader_core_properties.txt
We forgot to update the Status section when we published this extension.
Purely editorial so I didn't bump revisions for this.
=> Update Status of ARM_shader_core_properties

xml/gl.xml
=> Fix XML for GL_OES_EGL_image_external
