KhronosGroup/OpenGL-Registry

xml/gl.xml

This function is missing from the extension in the XML file.
Made this pull request as per the comment here https://www.khronos.org/bugzilla/show_bug.cgi?id=1923#c1
This pr closes https://github.com/Dav1dde/glad/issues/73
Cheers, Jakob.

Add glProgramParameteri to GL_ARB_separate_shader_objects

---

extensions/ARB/ARB_bindless_texture.txt

Update issue (19) to correct discussion of the DrawIDARB built-in and the name
of the extension that added it.

Fix typo in an ARB_bindless_texture issue.

---

extensions/EXT/EXT_polygon_offset_clamp.txt
extensions/NV/NV_gpu_multicast.txt

EXT_polygon_offset_clamp:  Update the "Version" section at the top of the file
to match the revision history at the bottom.
NV_gpu_multicast:  Fix a couple simple typos.

Typo fixes in several OpenGL extensions.

---

xml/gl.xml

This is needed for an upcoming CTS test which relies on
glTexturePageCommitmentEXT, which should be available in both
compatibility and core profiles.

Make GL_EXT_direct_state_access available in core profile

---

extensions/NV/NV_geometry_shader_passthrough.txt

Fix syntax issues in various sample code, including the introduction.
Passthrough inputs need to be declared as "arrayed" (with a separate block
instance for each vertex).  Added issue (18) to clarify further.

Fix incorrect syntax in NV_geometry_shader_passthrough examples.

---

api/GL/glcorearb.h
api/GL/glext.h
api/GLES/gl.h
api/GLES/glext.h
api/GLES2/gl2.h
api/GLES2/gl2ext.h
api/GLES3/gl3.h
xml/gl.xml

This fixes issue #29.
Because of the missing ```<ptype></ptype>``` around the new callback type the typedef definition of this was not generated. Also the old name "VULKANPROCNV" was in the wrong namespace. Now it's called "GLVULKANPROCNV".

Fix typedef generation of GLVULKANPROCNV

---

extensions/EXT/EXT_multisampled_render_to_texture2.txt
extensions/esext.php
extensions/registry.py

Adds EXT_multisampled_render_to_texture2 extension.
Discussion of the extension was tracked in Khronos-internal Bugzilla [16022](https://cvs.khronos.org/bugzilla/show_bug.cgi?id=16022).

Add EXT_multisampled_render_to_texture2

---

extensions/EXT/EXT_texture_compression_astc_decode_mode.txt
extensions/esext.php
extensions/registry.py
xml/gl.xml

Change-Id: I7e133e5f98896fd260cb7d20b4be2e62a01dbf9c
Adds EXT_texture_compression_astc_decode_mode extension.
Discussed in Khronos internal bug 16185.

Adding EXT_texture_compression_astc_decode_mode extension

---

api/GL/glext.h
api/GLES/gl.h
api/GLES/glext.h
api/GLES2/gl2.h
api/GLES2/gl2ext.h
api/GLES3/gl3.h
xml/gl.xml

Fix typo in headers for signature of FramebufferFoveationParametersQCOM.

Fix typo in function signature of FramebufferFoveationParametersQCOM

---

extensions/ARB/ARB_shader_ballot.txt

Reverse the sense of the GL_ARB_shader_ballot subgroup mask built-in variables

Reverse the sense of the GL_ARB_shader_ballot subgroup mask built-in variables

---

xml/gl.xml

Add 'glcore' to the supported attribute for a good number of ARB/NV extensions that can definitely be supported in the core profile.  I'm sure there are a lot more that could be yet, but it's not entirely clear what the criteria is. 
A couple of other tweaks for extensions that had incorrect supported fields as well.

Whitelist a number of ARB/NV extensions for glcore

---

xml/glxproto.reserved.txt

In X11 terms, the 'single' opcode is the minor opcode of the request,
which is eight bits.

glxproto: Fix single opcode size

---

xml/gl.xml

This pull request fills several missing enumerations

Create missing enumerations

---

xml/gl.xml

Unfortunately this didn't *just* add enum group information, it changed some parameter names and
types incorrectly.
Fixes #46.

Revert changes from #45. 

---

xml/gl.xml

This adds missing alias tags to following three functions:
* glGetGraphicsResetStatusEXT
* glGetnUniformfvEXT
* glGetnUniformivEXT

Add aliases to GL_EXT_robustness functions

---

api/GL/glext.h
api/GL/glxext.h
api/GL/wglext.h
api/GLES/gl.h
api/GLES/glext.h
api/GLES2/gl2.h
api/GLES2/gl2ext.h
api/GLES3/gl3.h
extensions/EXT/EXT_external_buffer.txt
extensions/esext.php
extensions/glext.php
extensions/registry.py
xml/gl.xml

This change adds multivendor extension EXT_external_buffer.  ARM, NVidia, Google, and QCOM were in support and all give it +1.    Was discussed in Khronos-internal [MR!13](https://gitlab.khronos.org/opengl/WG-Docs/merge_requests/13). 
Would like review by @dgkoch since this is my first GL-extension.

Add_EXT_external_buffer

---

extensions/OVR/OVR_multiview.txt

Fixes internal bugzillas 16173, 16174, 16176
CC @casseveritt, since you're the contact on these.

Clarify Blit and Clear behaviours, and fixed framebuffer attachment binding psuedocode

---

api/GL/glext.h
api/GL/glxext.h
api/GL/wglext.h
api/GLES/gl.h
api/GLES/glext.h
api/GLES2/gl2.h
api/GLES2/gl2ext.h
api/GLES3/gl3.h
xml/gl.xml

The OES_draw_elements_base_vertex spec specifies that the
glMultiDrawElementsBaseVertexEXT function be made available if
EXT_multi_draw_arrays is available. However the gl.xml (and generated
headers) used an OES suffix there by mistake.
Fixes #81

Fix suffix for glMultiDrawElementsBaseVertex

---

extensions/EXT/EXT_EGL_image_array.txt

Fix reference to extension as agreed in Khronos-internal  [WG-Docs Issue#6](https://gitlab.khronos.org/opengl/WG-Docs/issues/6)

Fix extension reference in EXT_EGL_image_array

---

README.adoc

The links on the front page of the github repository are brokens because the directory is /docs and not /doc.
This PR fix this issue.

Fixed docs links on the repository front page.

---

xml/gl.xml

byte, clampf, short, and ushort are not used by the API but were
historically provided by GLES/gl.h

Add types to GLES/gl.h for backwards compatibility

---

extensions/EXT/EXT_clip_control.txt
extensions/esext.php
extensions/registry.py
xml/gl.xml

This is a direct port of GL_ARB_clip_control to ES. The significant
difference from GL_ARB_clip_control is that this extension drops
language relevant to non-existent features in ES. In particular, it
drops language relevant to depth clamping and begin/end.
The Chrome browser can use this extension to improve the performance of
WebGL surface composition. It enables Chrome to render WebGL surfaces
directly into hardware overlays even when the display controller does
not support flipping the Y-axis at scanout.
Requested-by: David Reveman <reveman@google.com>
See-also: https://chromium-review.googlesource.com/c/603150/

GL_EXT_clip_control: New extension

---

api/GL/glcorearb.h
api/GL/glext.h
api/GL/glxext.h
api/GLES/gl.h
api/GLES/glext.h
api/GLES2/gl2.h
api/GLES2/gl2ext.h
api/GLES3/gl3.h
extensions/MESA/GLX_MESA_swap_control.txt
extensions/glext.php
extensions/registry.py
xml/gl.xml
xml/glx.xml

Apparently the state tokens BLEND_COLOR and BLEND_EQUATION weren't
included in the GL 1.4 core interfaces, although the corresponding entry
points were promoted from ARB_imaging to core. Also rearranged the subset of ARB_imaging tokens in both part of the XML to be in the same order, for slight clarity improvement.

Proposed fix for #103.

---

extensions/EXT/EXT_texture_mirror_clamp_to_edge.txt
extensions/Makefile
extensions/esext.php
extensions/registry.py
xml/gl.xml

OpenGL ES is missing an extension to expose MIRROR_CLAMP_TO_EDGE texture wrap mode.

Added EXT_texture_mirror_clamp_to_edge extension

---

api/GL/glext.h
extensions/MESA/MESA_tile_raster_order.txt
extensions/esext.php
extensions/glext.php
extensions/registry.py
xml/gl.xml

Some wording is new based on review feedback on the Mesa mailing list
-- version 1 had been looked at by Intel and AMD developers, and the
conclusion was that we needed to clarify TextureBarrier()'s role in
the list of exceptions given the new exception.
Implementation status: Kernel side ABI in place for vc4, piglit test
written and submitted, and Mesa implementation submitted.

Add a new MESA_tile_raster_order extension.

---

api/GL/glext.h
api/GLES/gl.h
api/GLES/glext.h
api/GLES2/gl2.h
api/GLES2/gl2ext.h
api/GLES3/gl3.h
xml/gl.xml

\<group> tags and removes the value= attributes in those groups, because
the scripts don't allow redefining enums (even benignly) inside \<enums>
tags.
I'm not certain what to do with the additions to ShaderType and they
have just been reverted, for the moment. Probably best is to use a
different group name (ShaderStages?) in a \<group> tag including all of
them.
@3b please make sure that after proposing a new PR addressing this, 'make'
executes and regenerates the headers, unchanged other than the revision
dates, without reporting any warnings or errors.

This moves some of the new enum groups introduced in #108 into distinct

---

extensions/OVR/OVR_multiview.txt

- Rebased on ES 3.2 (and OpenGL 4.6 where necessary) and added extension interactions
- Added DSA command for GL: NamedFramebufferTextureMultiviewOVR
- properly documented gl_ViewID_OVR and behaviour
- documented error behavior for num_views
- added error behavior for tess, geom, xfb, and timer queries
- documented new FRAMEBUFFER_ATTACHMENT*OVR variables
- clarify that only 2D-array textures are supported
- better document new framebuffer completeness conditions
- document MAX_VIEWS_OVR and specify minimum value (2)
- added issues 18-30

Completed OVR_multiview extension

---

api/GL/glxext.h
xml/glx.xml

The spec text and the Mesa implementation both had an int return here.
Found when updating the GL headers in Mesa broke the build of the
piglit test suite.

MESA_swap_interval: Fix typo of the return value in the XML

---

api/GL/glext.h
api/GL/glxext.h
api/GL/wglext.h
api/GLES/gl.h
api/GLES/glext.h
api/GLES2/gl2.h
api/GLES2/gl2ext.h
api/GLES3/gl3.h
extensions/QCOM/QCOM_texture_foveated.txt
extensions/esext.php
extensions/registry.py
xml/gl.xml

Add QCOM_texture_foveated which allows foveation to be specified on textures

Add GL_QCOM_texture_foveated

---

extensions/ARB/ARB_indirect_parameters.txt

Otherwise, there is no way to reliably write to a PARAMETER_BUFFER_ARB
from a shader.
Issue: https://github.com/KhronosGroup/OpenGL-API/issues/17

ARB_indirect_parameters: add COMMAND_BARRIER_BIT language

---

api/GL/glext.h
api/GL/glxext.h
api/GLES/gl.h
api/GLES/glext.h
api/GLES2/gl2.h
api/GLES2/gl2ext.h
api/GLES3/gl3.h
extensions/EXT/EXT_external_objects.txt
xml/gl.xml

VK_KHR_maintenance2 added two new image layouts
to Vulkan to allow more efficient use of packed
depth_stencil images.  This change adds
corresponding texture layouts to OpenGL.

Add new VK texture layouts to GL_EXT_semaphore

---

extensions/ARB/ARB_gl_spirv.txt

The noise*() functions in GLSL are deprecated and defined to return 0. But for SPIR-V, they should not be supported at all.

Noise functions are not present when generating SPIR-V.

---

api/GL/glext.h
api/GLES2/gl2ext.h
extensions/MESA/MESA_program_binary_formats.txt
extensions/esext.php
extensions/glext.php
extensions/registry.py
xml/gl.xml

This extension defines the GL_PROGRAM_BINARY_FORMAT_MESA
enum to be used by the ARB_get_program_binary and
OES_get_program_binary extensions.

Add MESA_program_binary_formats extension

---

xml/gl.xml

The extensions:
GL_EXT_debug_marker
GL_KHR_debug
GL_OES_surfaceless_context
GL_OES_texture_npot
can be supported in gles1 as well as gles2.
Closes #71

Add gles1 support for some extensions

---

extensions/ARB/ARB_gl_spirv.txt

https://github.com/KhronosGroup/OpenGL-API/issues/16

Clarify errors for glSpecializeShader

---

api/GL/glext.h
api/GL/glxext.h
api/GLES/gl.h
api/GLES/glext.h
api/GLES2/gl2.h
api/GLES2/gl2ext.h
api/GLES3/gl3.h
xml/gl.xml

Reserve buffer usage bit 0x2000 for NVX_cross_process_interop (which is not being published now). 
Also note that buffer usage bit 0x1000 was also previously reserved for NVIDIA.

reserve MapBufferUsageMask 0x2000 for NVX_cross_process_interop

---

extensions/MESA/GLX_MESA_copy_sub_buffer.txt

This pulls in the changes from Ian Romanick (@ianromanick) in Mesa commit
https://cgit.freedesktop.org/mesa/mesa/commit/?id=1f47388dfebf15f610993f046e1f945024c8fc3c
From Ian's commit:
> Copied language from the glXSwapBuffers manual page about the implicit
> glFlush and expected command completion.  This just codifies what
> people already expect from glXCopySubBufferMESA.  The intention of
> this command is to work like glXSwapBuffers but on a sub-rectangle of
> the drawable.

GLX_MESA_copy_sub_buffer: add language about implicit flush and command completion

---

extensions/MESA/GLX_MESA_release_buffers.txt

This pulls in the changes from Nicolas Kaiser (@nikai3d) in Mesa commit
https://cgit.freedesktop.org/mesa/mesa/commit/?id=ae5776c41f12515bb73c07ee2a0aed56cdd1a1ef

GLX_MESA_release_buffers: fix a couple typos

---

extensions/MESA/GLX_MESA_query_renderer.txt

This pulls in the changes from Emil Velikov (@evelikov) in Mesa commit
https://cgit.freedesktop.org/mesa/mesa/commit/?id=68bc1e2025db5bfbfdd77c5f3b47a4ac2db8fd8d

GLX_MESA_query_renderer: fix a couple typos

---

extensions/MESA/MESA_pack_invert.txt

This pulls in the changes from Nicolas Kaiser (@nikai3d) in Mesa commit
https://cgit.freedesktop.org/mesa/mesa/commit/?id=ae5776c41f12515bb73c07ee2a0aed56cdd1a1ef

MESA_pack_invert: fix typo

---

extensions/MESA/MESA_ycbcr_texture.txt

This pulls in the changes from Brian Paul and Nicolas Kaiser (@nikai3d) in Mesa commits
https://cgit.freedesktop.org/mesa/mesa/commit/?id=29f0190be772bc46ba2ddb4032e112f49d384cf5
https://cgit.freedesktop.org/mesa/mesa/commit/?id=fbb60ede3d5005328cedc9c2fa587e14e6309ed6
https://cgit.freedesktop.org/mesa/mesa/commit/?id=ae5776c41f12515bb73c07ee2a0aed56cdd1a1ef

MESA_ycbcr_texture: fix a few typos

---

xml/gl.xml

Length of _semaphores_ parameters changed from _count_, which doesn't exist in the commands, to _n_.

Fixed param lengths for glDeleteSemaphoresEXT and glGenSemaphoresEXT.

---

xml/gl.xml

_GLvoid_ was still being used in two extention commands.

Changed GLvoid to void in the rest of commands.

---

api/GL/glext.h
api/GL/glxext.h
api/GL/wglext.h
api/GLES/gl.h
api/GLES/glext.h
api/GLES2/gl2.h
api/GLES2/gl2ext.h
api/GLES3/gl3.h
extensions/NV/NV_clip_space_w_scaling.txt
extensions/NV/NV_stereo_view_rendering.txt
extensions/esext.php
extensions/registry.py
xml/gl.xml

This change updates two NVIDIA extensions and registers them in the OpenGL ES Registry.  I think I followed the directions properly for assigning numbers and updating various headers/XML files, but it would be good to double-check.
Note that this change also includes a fix to "registry.py", which had an incorrect prefix for MESA_program_binary_formats.  See the commit message for more info.

Register two NVIDIA extensions for OpenGL ES.

---

api/GL/glxext.h
extensions/EXT/GLX_EXT_no_config_context.txt
xml/glx.xml

There is significant interest in enabling on-screen HDR drawables under
X11. One awkward feature of GLX_ARB_fbconfig_float is that, since the
context and fbconfig must be compatible, a compositor wanting to consume
both integer and floating point drawables must use multiple contexts.
To address this, port EGL_KHR_no_config_context to GLX.

Add GLX_EXT_no_config_context

---

api/GL/glcorearb.h
api/GL/glext.h
api/GL/glxext.h
api/GLES/gl.h
api/GLES/glext.h
api/GLES2/gl2.h
api/GLES2/gl2ext.h
api/GLES3/gl3.h
extensions/NV/NV_conservative_raster_pre_snap.txt
extensions/NV/NV_conservative_raster_underestimation.txt
extensions/esext.php
extensions/glext.php
extensions/registry.py
xml/gl.xml

This PR registers the following new extensions:
- GL_NV_conservative_raster_pre_snap (GL and ES)
- GL_NV_conservative_raster_underestimation (GL only)

Register new GL_NV_conservative_raster* extensions

---

extensions/EXT/EXT_texture_sRGB_decode.txt

Per the discussion on API issue 51. Attempting to put the rules into
words became a mess, so I replaced it all with a table.
Note I also added the 'statically' which I believe came up in
earlier discussions on texelFetch, to make it clear that the
implementation is not required to solve the halting problem.

EXT_texture_sRGB_decode: add interaction with ARB_bindless_texture

---

extensions/OVR/OVR_multiview.txt

Clarify that compute shaders are orthogonal to multiview
framebuffers (Issue 31).

OVR_multiview version 3

---

extensions/EXT/EXT_primitive_bounding_box.txt
extensions/OES/OES_primitive_bounding_box.txt

The declaration of the variable was added to the ESSL spec, and it was described in the API spec, but there was no description of the variable in the ESSL spec itself.
Fixes gitlab OpenGL/GLSL#25.

Add description of gl_BoundingBox* to ESSL spec

---

api/GL/glext.h
api/GL/glxext.h
api/GL/wglext.h
api/GLES/gl.h
api/GLES/glext.h
api/GLES2/gl2.h
api/GLES2/gl2ext.h
api/GLES3/gl3.h
extensions/EXT/EXT_EGL_image_external_wrap_modes.txt
extensions/esext.php
extensions/registry.py

This adds the named extension as was agreed in Khronos-internal  [MR!11](https://gitlab.khronos.org/opengl/registry/merge_requests/11).

Add EXT_EGL_image_external_wrap_modes

---

extensions/ARB/ARB_gl_spirv.txt
extensions/ARB/ARB_spirv_extensions.txt

- Add whitelist of accepted storage classes 
(https://gitlab.khronos.org/spirv/SPIR-V/issues/166)
- Require *Binding* for block variables in SPIR-V
(https://gitlab.khronos.org/opengl/API/issues/55)

Updates for ARB_gl_spirv and ARB_spirv_extensions

---

api/GL/glcorearb.h
api/GL/glext.h
api/GLES2/gl2ext.h
extensions/EXT/EXT_shader_framebuffer_fetch.txt
extensions/esext.php
extensions/glext.php
extensions/registry.py
xml/gl.xml

Merge request from the gitlab repository with a number of improvements for the EXT_shader_framebuffer_fetch extension, including desktop GL support and a non-coherent variant of the extension with potentially better performance/wider hardware support.

Improvements for EXT_shader_framebuffer_fetch

---

extensions/ARB/ARB_internalformat_query2.txt

Add issue 16.
Clarify that GetInternalFormat* commands shouldn't be restricted
by GetTexLevelParameter valid parameters.
Gitlab opengl/API Issue: 65

ARB_internalformat_query2 revision 19

---

api/GL/glext.h
api/GLES/gl.h
api/GLES/glext.h
api/GLES2/gl2.h
api/GLES2/gl2ext.h
api/GLES3/gl3.h
extensions/EXT/EXT_texture_format_sRGB_override.txt
extensions/esext.php
extensions/registry.py
xml/gl.xml

Adds the named extension as approved in https://gitlab.khronos.org/opengl/registry/merge_requests/10

Add EXT_texture_format_sRGB_override

---

xml/readme.tex

The description of "alias" and "vecequiv" tags in 12.2
does not reflect what's actually in gl.xml. The readme says
that these tags do not have any attributes and contain strings.
In gl.xml, however, these tags are empty and the relevant values
are contained within their "name" attributes. For example:
```
<command>
<proto>void <name>glBinormal3dEXT</name></proto>
<param group="CoordD"><ptype>GLdouble</ptype> <name>bx</name></param>
<param group="CoordD"><ptype>GLdouble</ptype> <name>by</name></param>
<param group="CoordD"><ptype>GLdouble</ptype> <name>bz</name></param>
**<vecequiv name="glBinormal3dvEXT"/>**
</command>
```
and
```
<command>
<proto>void <name>glBlendColorEXT</name></proto>
<param group="ColorF"><ptype>GLfloat</ptype> <name>red</name></param>
<param …
```

Amend section 12.2 of readme (<alias> and <vecequiv> tags)

---

api/GL/glcorearb.h
api/GL/glext.h
api/GLES/gl.h
api/GLES/glext.h
api/GLES2/gl2.h
api/GLES2/gl2ext.h
api/GLES3/gl3.h
extensions/INTEL/INTEL_blackhole_render.txt
extensions/esext.php
extensions/glext.php
extensions/registry.py
xml/gl.xml

Add INTEL_blackhole_render to t the OpenGL & OpenGL ES extension
registry. Regenerates headers files.

Register new INTEL_blackhole_render extension for OpenGL & OpenGL ES

---

xml/gl.xml

"near" and "far" conflict with macros defined by windows.h

Rename parameters of glDepthRangef to "n" and "f"

---

extensions/AMD/AMD_gpu_shader_half_float_fetch.txt

Add some missing function prototypes when this extension interacts with
AMD_texture_gather_bias_lod.

Update the spec of AMD_gpu_shader_half_float_fetch (Rev. 6)

---

xml/gl.xml

Adding missing length information values for pointer parameters of the disjoint timer query and robustness extension functions

Adding len value to gl.xml

---

xml/reg.py

Several headers have the same header guard, making it impossible to
include declarations from both headers. This was complicating the
implementation of a driver with support for both desktop OpenGL and
OpenGL ES.

Include the API name in the header guard.

---

extensions/EXT/EXT_EGL_image_storage.txt
extensions/registry.py
xml/gl.xml

This extension allows the creation of immutable texture EGLImage targets.
These have much simpler semantics than regular texture EGLImage targets
defined by OES_EGL_image and do not exhibit potentially surprising and
undesirable orphaning behavior.

Add EXT_EGL_image_storage extension.

---

xml/gl.xml

The vector versions are not properly annotated with the lengths, and the
scalar versions don't reference the vector versions.

gl.xml: Add len attribute and veequiv tags for DrawTexOES

---

extensions/KHR/KHR_blend_equation_advanced.txt
extensions/NV/NV_blend_equation_advanced.txt

Fixes https://www.khronos.org/members/login/bugzilla/show_bug.cgi?id=16026 and https://gitlab.khronos.org/opengl/API/issues/60.
Fix the HSL blend equation ClipColor() pseudo-code and modify the spec to say that the HSL blend equations are only well defined when the input color components are in the range [0..1].
Once this is approved we need to update the OpenGL ES 3.2 spec with the same change.

Fix HSL ClipColor() equation in the blend_equation_advanced extensions

---

extensions/ARB/ARB_gl_spirv.txt

Clarify that OpImageQuerySizeLod and OpImageQuerylevels only work with Sampled images
(SPIR-V/issues/280)

OpImageQuerySizeLod and OpImageQuerylevels only work with Sampled images

---

extensions/glext.php
extensions/registry.py

For some reason GLX_EXT_stereo_tree was listed on
the registry page as GL_EXT_glx_stereo_tree.  This
change just corrects it to GLX_EXT_stereo_tree.

Fix link name for GLX_EXT_stereo_tree in registry

---

extensions/EXT/EXT_multisampled_render_to_texture.txt

Change-Id: I8999e44deb5e541bfdedfaa69a9b55c9cb164d41
No functional change, but reworded to make the expected behavior more clear.

Clarify resolve behavior in EXT_multisampled_render_to_texture

---

extensions/ARB/ARB_gl_spirv.txt

This resolves internal issue https://gitlab.khronos.org/opengl/API/issues/70.
This clarifies that OpenGL allows SPIR-V shaders to use multi-dimensional arrays for resources like UBOs and SSBOs, in that same way that OpenGL allows this for GLSL shaders. This is a difference to the SPIR-V environment for Vulkan, which only allows single-dimension arrays for these resources.

Clarify arrays of arrays is allowed for resources

---

extensions/OVR/OVR_multiview.txt

Edits to OVR_multiview for desktop. Whenever a multiview framebuffer is bound, these edits make the results of glBegin/ glEnd undefined and the contents of gl_Layer in the fragment shader undefined. Also
clarifies what happens when a transform feedback object is paused.

OVR_multiview version #4

---

extensions/OML/GLX_OML_sync_control.txt

This seems to just be an error. GLX_SBC is not in fact a defined token,
and it's not clear what its value would even be, as the SBC is a
property of the drawable not the fbconfig.

GLX_OML_sync_control: Remove spurious GLXFBConfig attribute

---

api/GL/glcorearb.h
api/GL/glext.h
api/GLES/gl.h
api/GLES/glext.h
api/GLES2/gl2.h
api/GLES2/gl2ext.h
api/GLES3/gl3.h
xml/gl.xml

Fix conflicting type declarations in GL and GLES.
Fixes #162
Fixes #97

Fix conflicting type declarations in GL and GLES

---

extensions/EXT/EXT_texture_filter_anisotropic.txt

This came up in https://bugs.chromium.org/p/angleproject/issues/detail?id=2072

Clarify anisotropic extension interaction with sampler objects.

---

extensions/ARB/ARB_gl_spirv.txt

Clarify that the atomicCounterDecrement -> OpAtomicIDecrement mapping includes 
a post-decrement
https://github.com/KhronosGroup/OpenGL-API/issues/38

ARB_gl_spirv revision 40

---

api/GL/wglext.h

The value for WGL_COLORSPACE_EXT is 0x309D as per extension's specification, not 0x3087. Also, tested on the newest NVIDIA drivers and only the value 0x309D is correctly recognized.

Wrong value for the WGL_EXT_colorspace extension

---

xml/gl.xml

Support contexts that only expose GL_EXT_robustness

Alias glGetGraphicsResetStatusEXT to core function

---

xml/gl.xml

GL_ACTIVE_TEXTURE and GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS were missing from GetPName. This is a valid value for ES2.0. Reference: https://www.khronos.org/registry/OpenGL-Refpages/es2.0/xhtml/glGet.xml

Add missing enum values to group "GetPName" in file gl.xml

---

extensions/OVR/OVR_multiview.txt

If baseViewIndex + numViews is equal to the value of MAX_ARRAY_TEXTURE_LAYERS, then the layer pointed to by the last view can still fit into a 2D array texture.

Fix off-by-one in baseViewIndex + numViews check

---

extensions/EXT/EXT_shader_framebuffer_fetch.txt

Found this issue when diffing specs held in separate source code control systems.

EXT_shader_framebuffer_fetch:  Fix non-ASCII quotes.

---

xml/gl.xml

All of the NVIDIA Turing extensions are supported in the core
profile.  But they currently don't appear in glcorearb.h because I
used 'supported="gl"' instead of 'supported="gl|glcore"' in gl.xml.
@oddhack @pixeljetstream

Fix NVIDIA Turing extensions to appear in glcorearb.h.

---

extensions/NV/NV_sample_locations.txt

GLEW is still parsing extension specs, is expecting void argument which is common convention for these.

NV_sample_locations void function argument (by formatting conventions)

---

api/GL/glext.h
api/GL/glxext.h
api/GL/wgl.h
api/GL/wglext.h
api/GLES/gl.h
api/GLES/glext.h
api/GLES2/gl2.h
api/GLES2/gl2ext.h
api/GLES3/gl3.h
extensions/NV/NV_vdpau_interop2.txt
extensions/glext.php
extensions/registry.py
xml/gl.xml

This change adds new extension vdpau_interop2 which
adds API's glVDPAURegisterVideoSurfaceWithPictureStructureNV.
so that applications can specify whether they want to recieve
field-based or frame-based surfaces.This is identical to the
existing VDPAURegisterVideoSurfaceNV(), but will pass additional
field-vs-frame parameter.

WIP: Add API's in VDPAU interop to receive frame/field-based surface

---

extensions/OVR/OVR_multiview.txt
extensions/OVR/OVR_multiview2.txt

Per internal gitlab issue
https://gitlab.khronos.org/opengl/API/issues/96
- add boiler plate shading language text about #define
- clarify that OVR_multiview2 implicitly enables OVR_multiview

OVR_multiview/2 clarifications

---

extensions/QCOM/QCOM_YUV_texture_gather.txt
extensions/registry.py
xml/gl.xml

Adds vendor extension QCOM_YUV_texture_gather as discussed in Khronos-internal [MR17](https://gitlab.khronos.org/opengl/registry/merge_requests/17)

add QCOM_YUV_texture_gather

---

extensions/ARB/ARB_internalformat_query2.txt
xml/gl.xml

Add view compatibility classes for EAC/ETC2 and ASTC formats
and add them for ARB_internalformat_query2.
These are mentioned in EXT/OES_texture_view for ES, but they
are never externally visibile and thus weren't assigned tokens.
However we also support these formats natively in GL on some
platforms, so we need tokens to return when the VIEW_COMPATIBILITY_CLASS
is queried on those platforms.
Reserve tokens for the VIEW_CLASSes for ASTC_3D, but don't
actually enable them since there are no extensions which
add these for GL.

Define tokens for VIEW_CLASS_{EAC*,ETC2*,ASTC*}

---

extensions/NV/NV_vdpau_interop2.txt

This change marks the new extension vdpau_interop2 as complete.
Extension vdpau_interop2 adds API
glVDPAURegisterVideoSurfaceWithPictureStructureNV so that applications 
can specify whether they want to receive field-based or frame-based 
surfaces

Mark vdpau_interop2 to receive frame/field-based surface as complete

---

api/GL/glxext.h
extensions/MESA/GLX_MESA_query_renderer.txt
xml/glx.xml

This syncs the spec with the version in Mesa git:
https://gitlab.freedesktop.org/mesa/mesa/merge_requests/21
There is one detail here I'm not sure of, which is that the XML now no longer defines `GLX_RENDERER_ID_MESA`. I believe this is safe, in that the Mesa code has never actually implemented the behavior formerly specified for that token so there can't really be extant code that depends on it working. But if the OpenGL rules are that you can't unpublish an enum then I'm fine with leaving it defined and just noting that it doesn't do anything.

Update GLX_MESA_query_renderer spec to v9

---

extensions/ARB/ARB_gl_spirv.txt

These changes will be reflected in the next OpenGL 4.6 spec update as well, once that's published.

Explicitly give rules for SPIR-V uniform offsets. 

---

extensions/NV/NV_gpu_multicast.txt
extensions/NV/NV_mesh_shader.txt

NV_gpu_multicast:  Reduce the MULTICAST_GPUS_NV minimum to 1.  Clarify
that MULTICAST_GPUS_NV is constant for a context.
NV_mesh_shader:  Fix a typo in language prohibiting use of a task
shader without a mesh shader.

Publish minor NVIDIA extension spec edits.

---

xml/wgl.xml

I'm migrating GLEW WGL support to use the XML as the source of truth.
I came across some minor discrepancies with the type and name of some parameters.
The relevant specification documents are:
https://www.khronos.org/registry/OpenGL/extensions/NV/NV_present_video.txt
https://www.khronos.org/registry/OpenGL/extensions/AMD/WGL_AMD_gpu_association.txt
https://www.khronos.org/registry/OpenGL/extensions/OML/WGL_OML_sync_control.txt

Align WGL XML parameter names and types to specifications

---

extensions/EXT/EXT_depth_clamp.txt
extensions/esext.php
extensions/registry.py
xml/gl.xml

This extension provides the same interaction for OpenGL ES that ARB_depth_clamp does for OpenGL.
I went for an EXT extension because it is based on this already available ARB extension, and for that reason it makes sense to me to get it fully approved, but I could also put it in the MESA namespace (since there I will implement it). Many thanks for any comments.

Register EXT_depth_clamp for GLES

---

xml/gl.xml

This PR introduces a new enum group to _gl.xml_, BufferStorageMask.
Up until now, glBufferStorage related methods used MapBufferUsageMask as the bitfield type:
```xml
<command>
<proto>void <name>glBufferStorage</name></proto>
<param group="BufferStorageTarget"><ptype>GLenum</ptype> <name>target</name></param>
<param><ptype>GLsizeiptr</ptype> <name>size</name></param>
<param len="size">const void *<name>data</name></param>
<param group="MapBufferUsageMask"><ptype>GLbitfield</ptype> <name>flags</name></param>
</command>
```
Not only is the name confusing, but MapBufferUsageMask also contained values which were not valid parameters for glBufferStorage:
```xml
<enums namespace="GL" group="MapBufferUsageMask" type="bitmask">
...
<enum value="0x0004" name="GL_MAP_INVALIDATE_RANGE_BIT"/>
<enum …
```

gl.xml: Add BufferStorageMask for glBufferStorage

---

extensions/ARB/ARB_texture_filter_anisotropic.txt

This minor update resolves issue 4 in GL_ARB_texture_filter_anisotropy with what the OpenGL working group agreed in https://gitlab.khronos.org/opengl/API/issues/47.

Update issue 4 in GL_ARB_texture_filter_anisotropy

---

xml/gl.xml

The [glDrawElementsInstancedBaseVertexBaseInstance](https://www.khronos.org/opengl/wiki/GLAPI/glDrawElementsInstancedBaseVertexBaseInstance) `type` parameter accepts values of `GL_UNSIGNED_BYTE`, `GL_UNSIGNED_SHORT`, or `GL_UNSIGNED_INT`. These are members of the `DrawElementsType` group, not the `PrimitiveType` group.

Fix the group name of the type parameter in glDrawElementsInstancedBaseVertexBaseInstance

---

extensions/ARB/ARB_gl_spirv.txt

ARB_gl_spirv: updates after internal API issues 99 and 100
This includes add references to uniform initializers, that was agreed
to be supported, and adding issue 28, about interaction with
ARB_get_program_binary. The text for the latter is based on Daniel
Koch's comment during the discussion of the internal API issue #100.

Fix internal 99 and 100 API issues

---

extensions/ARB/ARB_shader_viewport_layer_array.txt

gitlab/opengl/api/issue/44
Add shading language extension boiler plate language.
Clarify that the new built-ins should be members of
the "out gl_PerVertex" block.
Update the gl_Layer and gl_ViewportIndex built-in language
based on the language on in NV_viewport_array2.

Updates to ARB_shader_viewport_layer_array

---

extensions/EXT/EXT_texture_query_lod.txt
extensions/registry.py

This extension is a rewrite of  ARB_texture_query_lod  to provide this functionality in OpenGL ES.

Add extension EXT_texture_query_lod for GLES

---

extensions/NV/NV_shading_rate_image.txt
extensions/esext.php
extensions/registry.py
xml/gl.xml

Allows implementing with ES. If so, removes references to MULTISAMPLE
and double and adds MAX_VIEWPORTS and GetFloati_v alternatives.

Adds ES interactions to NV_shading_rate_image

---

extensions/EXT/EXT_multisampled_render_to_texture.txt
xml/gl.xml

@pdaniell-nv review & approve when ready. Perhaps the extension should say something about the confusing nature of the aliasing in practice?
N.b. this has no impact on the headers.

Revert removal of aliasing between RenderbufferStorageMultisample{,EXT} in #258

---

xml/gl.xml

I haven't done the archaeology to figure out what happened here. My
guess is that TypeEnum was intended as a catch-all for queriable
enumerant tokens, which are not realistically possible to list, and then
at some point it got used by the BeginConditionalRender commands.
While it isn't a complete fix, I changed the name of this group to
"ConditionalRenderMode" and used it only with those commands, and
removed the tagging of "TypeEnum" for the generic query commands.
Hopefully that won't subvert any outside use of the "TypeEnum" group.

Fix bogus use of enum group "TypeEnum"

---

xml/gl.xml

I founded 3 duplicate enum values in groups while I generate a C# bindings.

Removed duplicate enum values.

---

extensions/QCOM/QCOM_YUV_texture_gather.txt

Fixes a two typos in this vendor extension.

Fix typo in QCOM_YUV_texture_gather

---

xml/gl.xml

I founded other duplicate enum value while creating a OpenGLES 3.2 C# bindings.

Remove a duplicate InternalFormat enum value.

---

api/GL/glxext.h
extensions/EXT/GLX_EXT_context_priority.txt
extensions/glext.php
extensions/registry.py
xml/glx.xml

Copied from the corresponding EGL extension. This does not yet update
the XML for the new enumerants, pending resolution of the issues
mentioned in the extension spec.

glx: Add GLX_EXT_context_priority

---

api/GL/glcorearb.h
api/GL/glext.h
api/GL/glxext.h
api/GL/wgl.h
api/GL/wglext.h
api/GLES/gl.h
api/GLES/glext.h
api/GLES2/gl2.h
api/GLES2/gl2ext.h
api/GLES3/gl3.h
extensions/EXT/EXT_texture_shadow_lod.txt
extensions/esext.php
extensions/glext.php
extensions/registry.py
xml/gl.xml

This extension adds new overloaded textureLod and textureLodOffset
functions by including support for the shadow sampler types
sampler2DArrayShadow, samplerCubeShadow, and samplerCubeArrayShadow.

Adding EXT_texture_shadow_lod

---

extensions/EXT/EXT_texture_shadow_lod.txt

Simple update to EXT_texture_shadow_lod to correct a misspelling of a contributor's name.

EXT_texture_shadow_lod

---

api/GL/glcorearb.h
api/GL/glext.h
api/GL/glxext.h
api/GL/wgl.h
api/GL/wglext.h
api/GLES/gl.h
api/GLES/glext.h
api/GLES2/gl2.h
api/GLES2/gl2ext.h
api/GLES3/gl3.h
extensions/MESA/MESA_framebuffer_flip_y.txt
extensions/glext.php
extensions/registry.py
xml/gl.xml

This commit extends `GL_MESA_framebuffer_flip` to also work with GL 4.3, in
addition to GLES 3.1. We add a GL extension number, modify the XML
registry and rebuild generated sources.
GL 4.3 is needed for `FrameBufferParameteri` to be available.
I created a related merge request in Mesa [here](https://gitlab.freedesktop.org/mesa/mesa/merge_requests/1002). The Mesa MR will be updated after this pull request has been approved. Testing has been done as described in the Mesa MR.
The use case here is to use framebuffer objects to render into externally managed swap-chain images, which are directly scanned out by the display subsystem. Since framebuffer objects by default have their origin in the lower-left corner, but scan-out happens from top to bottom, content would appear upside-down. This …

Extend GL_MESA_framebuffer_flip_y to GL 4.3+

---

api/GL/glcorearb.h
api/GL/glext.h
api/GL/glxext.h
api/GL/wgl.h
api/GL/wglext.h
api/GLES/gl.h
api/GLES/glext.h
api/GLES2/gl2.h
api/GLES2/gl2ext.h
api/GLES3/gl3.h
extensions/KHR/KHR_shader_subgroup.txt
extensions/NV/NV_shader_subgroup_partitioned.txt
extensions/NV/WGL_NV_multigpu_context.txt
extensions/NVX/NVX_gpu_multicast2.txt
extensions/NVX/NVX_progress_fence.txt
extensions/arbext.php
extensions/esext.php
extensions/glext.php
extensions/registry.py
xml/genheaders.py
xml/gl.xml
xml/wgl.xml

Replaces #287, since I can't update @rbiermann's branch in-place in their repository. Changes one extension number to avoid collision with recently merged MESA extension. I was unable to clone their branch into this repo and successfully merge it - some sort of commit history incompatibility - so just did a patch against master in this branch, instead. 
@dgkoch @pdaniell-nv I suggest adding the KHR extension to this branch.
Unfortunately, the changes in #287 directly updated the headers rather than adding the new interfaces to gl.xml / wgl.xml. As a result regenerating the headers will not actually include the interfaces for the new extensions. If you can attempt to add the interfaces for the new extensions introduced in #287 that would be great. If not I'll attempt to do it, but I can't …

Add NVX_gpu_multicast2 (revised)

---

xml/gl.xml

#109 revealed some enum groups are missing, since then i have made two attempts at fixing all the enum groups, last time i only managed to fix a few but as far as i can see this PR adds the rest of the enum groups.
Regarding #280 
I hope this would also enable khronos to in the future keep the enum groups up to date as that wouldn't require nearly as much work as this was

Add missing enum groups

---

extensions/AMD/AMD_gpu_shader_half_float.txt

The key word of FLOAT16_MAT4x3_AMD should should be f16mat4x3

---

api/GL/glxext.h
extensions/NV/GLX_NV_multigpu_context.txt
extensions/glext.php
extensions/registry.py
xml/glx.xml

Adding GLX_NV_multigpu_context extension, see https://github.com/KhronosGroup/OpenGL-Registry/pull/287 for the WGL equivalent.  Please review and merge.
Thanks,
Ben Quest (NVIDIA)

Adding GLX_NV_multigpu_context extension

---

extensions/NV/NV_mesh_shader.txt

The minimum required implementation limit for GL_MAX_DRAW_MESH_TASKS_COUNT_NV should have been 2^16-1 and not 2^32-1.

Fix the required minimum limit for MAX_DRAW_MESH_TASKS_COUNT_NV

---

api/GL/glcorearb.h
api/GL/glext.h
api/GL/glxext.h
api/GLES/gl.h
api/GLES/glext.h
api/GLES2/gl2.h
api/GLES2/gl2ext.h
api/GLES3/gl3.h
extensions/EXT/EXT_EGL_sync.txt
extensions/glext.php
extensions/registry.py
xml/gl.xml

This PR adds the `GL_MESA_EGL_sync` OpenGL extension to extend
`EGL_KHR_fence_sync` with OpenGL client API support.
While arguably OpenGL already has `GL_ARB_sync`, there are platform
extensions that are layered on top `EGL_KHR_fence_sync` rather than
`GL_ARB_sync`. Without OpenGL support of `EGL_KHR_fence_sync`, these
extension can't be used with an OpenGL command stream. One notable
example is the `EGL_ANDROID_native_fence_sync` extension, which enables
`linux_sync_file` objects to be used as the backend of EGL sync objects.
Linux sync file objects can be used to synchronize buffer access between
processes dispatching OpenGL drawing commands, or to synchronize with
the Linux KMS display subsystem (aka 'explicit fencing').
There is a corresponding Mesa merge-request …

Add GL_MESA_EGL_sync extension

---

xml/gl.xml

Some OES enums are missing groups. Fix for #308 
Also fixes duplicate `GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME` enum in `FramebufferAttachmentParameterName` group and replaces the second instance with `GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE` enum which it probably should be.

Add OES enums to groups

---

extensions/ARB/ARB_framebuffer_sRGB.txt

Update the text to mention the GLX 1.3 entrypoints and specify the
selection and sorting behavior.
Resolves: https://github.com/KhronosGroup/OpenGL-Registry/issues/199

ARB_framebuffer_sRGB: Clarify interaction with GLX

---

extensions/ARB/ARB_tessellation_shader.txt

Fix typo in quad tessellation.

---

xml/gl.xml

`GL_MAX_COLOR_ATTACHMENTS` is not framebuffer attachment.
`GL_STENCIL_ATTACHMENT` (and `EXT` and `OES` variants) are framebuffer attachments.
Fix proposal for #313

Fixes to FramebufferAttachment enum group

---

xml/gl.xml

`ReadbufferMode` should include `GL_NONE`.
Fix proposal for #315

[gl.xml] Add GL_NONE to ReadBufferMode

---

xml/gl.xml

Add a variation of `FramebufferAttachment` enum group for `glDiscardFramebuffer()` and `glInvalidate*Framebuffer()` attachments which also accepts `GL_COLOR`, `GL_DEPTH` and `GL_STENCIL` attachments.
Fix proposal for #317

[gl.xml] Add InvalidateFramebufferAttachment enum group

---

api/GLES3/gl3.h
api/GLES3/gl31.h
api/GLES3/gl32.h
api/GLSC2/glsc2.h
api/GLSC2/glsc2ext.h

These were forgotten in dd9888c1ad20a1e8c502 ("Regenerated headers with
new format header guards that don't prevent").

regenerate GLES3 & GLSC2 headers

---

extensions/SGIX/SGIX_fragment_specular_lighting.txt

Align this extension with the XML/glext.h:
```
void GetFragmentMaterialfvSGIX(enum face, enum pname, float *data);
void GetFragmentMaterialivSGIX(enum face, enum pname, int *data);
```
```
typedef void (APIENTRYP PFNGLGETFRAGMENTMATERIALFVSGIXPROC) (GLenum face, GLenum pname, GLfloat *params);
typedef void (APIENTRYP PFNGLGETFRAGMENTMATERIALIVSGIXPROC) (GLenum face, GLenum pname, GLint *params);
```
In relation to https://github.com/nigels-com/glew/pull/239

SGIX_fragment_specular_lighting const getter fixup

---

xml/gl.xml

`glMultiDrawArrays` had incorrect param len for `first` parameter.
Fix for #325

[gl.xml] Fix glMultiDrawArrays() param len expression

---

extensions/ARB/ARB_texture_compression_bptc.txt

As discussed in issue #310, the "shared p-bits" specification in the ARB_texture_compression_bptc extension did not match what's in the Khronos Data Format spec (https://www.khronos.org/registry/DataFormat/specs/1.3/dataformat.1.3.html) or the DX spec.
This PR fixes that and closes #310.

Fix "shared p-bits" specification in ARB_texture_compression_bptc

---

xml/gl.xml

From EXT_disjoint_timer_query spec:
"Interaction: This extension adds GetInteger64vEXT if
OpenGL ES 3.0 is not supported"
Signed-off-by: Tapani Pälli <tapani.palli@intel.com>

[gl.xml] add glGetInteger64vEXT to EXT_disjoint_timer_query

---

extensions/NV/NV_alpha_to_coverage_dither_control.txt

Resolution for GLEW Issue: https://github.com/nigels-com/glew/issues/245
Align `AlphaToCoverageDitherControlNV` specification with norms.

Tidy-up for NV_alpha_to_coverage_dither_control extension specification

---

extensions/ARB/ARB_direct_state_access.txt

Aligning with `glext.h`
```
GLAPI void APIENTRY glClearNamedFramebufferfv (GLuint framebuffer, GLenum buffer, GLint drawbuffer, const GLfloat *value);
```
In relation to https://github.com/nigels-com/glew/issues/246

const fixup for ARB_direct_state_access ClearNamedFramebufferfv value

---

extensions/EXT/EXT_texture_compression_bptc.txt

This is a follow-on to https://github.com/KhronosGroup/OpenGL-Registry/pull/322, which fixed the "shared p-bits" for ARB_texture_compression_bptc. This makes the same fix to the OpenGL ES EXT_texture_compression_bptc.

Fix "shared p-bits" specification in EXT_texture_compression_bptc

---

extensions/EXT/EXT_disjoint_timer_query.txt

Also add an Interactions section specifying that it is only required when only OpenGL ES 2.0 is
supported.
Closes #326

Add specification language for GetInteger64v to EXT_disjoint_timer_query

---

xml/gl.xml

Closes #350 
- It feels weird putting NVIDIA functions in an ARB extension. Perhaps this isn't the right place for them.
- ARB_viewport_array is supported on both the core and compatibility profiles, whereas NV_depth_buffer_float is only supported on the compatibility profile. I'm not sure whether it's appropriate for compatibility-only functions to be referenced from a core extension

Add missing interactions between ARB_viewport_array and NV_depth_buffer_float

---

extensions/EXT/EXT_texture_compression_s3tc.txt
extensions/EXT/EXT_texture_compression_s3tc_srgb.txt

These parts define _editing_ of compressed textures and refer to offsets, so `*SubImage*` functions should be used.

Fix typos in S3TC

---

extensions/EXT/EXT_primitive_bounding_box.txt

It is unexpected that name string would have space in it.
Fix proposal for #372

Fix EXT_primitive_bounding_box name string

---

extensions/KHR/KHR_debug.txt

Section 5.5.2 mentions that asynchronous debug output is further described in section 5.5.6, but it actually is described in section 5.5.7.

Fix section misnumbering in GL_KHR_debug

---

api/GL/glext.h
api/GLES/gl.h
api/GLES/glext.h
api/GLES2/gl2.h
api/GLES2/gl2ext.h
api/GLES3/gl3.h
xml/gl.xml

More enums..
We have a few spare ones in the current Arm-reserved range, but I'd like a larger set of consecutive ones.

Reserve enums 0x96C0..0x96CF for Arm

---

extensions/NV/NV_shading_rate_image.txt

The old version of the spec created a prototype for
ShadingRateSampleOrderNV by copy-pasting the definition for
ShadingRateImageBarrierNV.  Unfortunately, that copy-paste failed to
fix the function name, so we have two instances of
ShadingRateImageBarrierNV.

Fix typo in the New Procedures section of NV_shading_rate_image.

---

extensions/NV/NV_gpu_multicast.txt

clarify that the interactions with uniform APIs only apply to
EXT_bindable_uniform (not ARB_uniform_buffer_object).
optionally allow MulticastCopyBufferSubDataNV with buffers lacking
per-GPU storage

Publish NVIDIA update to NV_gpu_multicast not pushed t

---

extensions/ANGLE/ANGLE_depth_texture.txt

Discovered this was never updated while reviewing https://github.com/KhronosGroup/WebGL/pull/3042 .

Update ANGLE_depth_texture extension from ANGLE project's repo.

---

api/GLES2/gl2ext.h
extensions/QCOM/QCOM_motion_estimation.txt
extensions/esext.php
extensions/registry.py
xml/gl.xml

Adds and extension to OpenGL ES for comparing two textures and generation resulting motion vector image.

add QCOM_motion_estimation

---

extensions/ARB/ARB_copy_image.txt

PBTC was used instead of BPTC.

Typo in ARB_copy_image #385

---

api/GL/glext.h
api/GL/glxext.h
api/GL/wgl.h
api/GL/wglext.h
api/GLES/gl.h
api/GLES/glext.h
api/GLES2/gl2.h
api/GLES2/gl2ext.h
api/GLES3/gl3.h
extensions/MESA/MESA_framebuffer_flip_x.txt
extensions/MESA/MESA_framebuffer_swap_xy.txt
extensions/esext.php
extensions/glext.php
extensions/registry.py
xml/gl.xml

GL_MESA_framebuffer_swap_xy and GL_MESA_framebuffer_flip_x are used
together with GL_MESA_framebuffer_flip_y to implement the
pre-rotation feature.

Add GL_MESA_framebuffer_flip_x and GL_MESA_framebuffer_swap_xy

---

extensions/ARB/ARB_texture_query_lod.txt

The original requirement of OpenGL version 2.0 and OpenGL Shading
language version 1.30 was inconsistent, as it is not possible a driver
exposing both is not possible. Updating the OpenGL version required.
This fixes the internal API issue 124.

ARB_texture_query_lod: update OpenGL version needed

---

extensions/QCOM/QCOM_shading_rate.txt

This PR makes a minor change to QCOM_shading_rate extension, relaxing the guaranteed shading rate when PRESERVE_SHADING_RATE_ASPECT_RATIO is not set.

relax QCOM_shading_rate extension

---

api/GL/glcorearb.h
api/GL/glext.h
api/GLES/gl.h
api/GLES/glext.h
api/GLES2/gl2.h
api/GLES2/gl2ext.h
api/GLES3/gl3.h
xml/gl.xml

Add support for GL to generate the extensions for GL extension header (which was missing at commit 6b670cbfa807378e46c7e704b2980561279304f3).

GL_MESA_framebuffer_flip_x/swap_xy: Generate extensions for GL extension header

---

xml/gl.xml

These are part of GetPName enum group:
- GL_MAX_TESS_CONTROL_UNIFORM_BLOCKS
- GL_MAX_TESS_EVALUATION_UNIFORM_BLOCKS
- GL_CONTEXT_PROFILE_MASK

Additions to GetPName enum group

---

xml/gl.xml

BufferPNameARB is generic while VertexBufferObjectParameter
was incorrectly too specific.
BufferPointerNameARB is correct group for pointer queries.

Use BufferPNameARB and BufferPointerNameARB as enum group

---

xml/gl.xml

GetTransformFeedbackVarying() was using incorrect GlslTypeToken
enum group for type parameter. The correct enum group is
AttributeType.

GetTransformFeedbackVarying: GlslTypeToken > AttributeType

---

xml/gl.xml

glVertexAttribIPointer() to use VertexAttribIType enum group for
type parameter.
glVertexAttribLPointer to use VertexAttribLType enum group for
type parameter.

Strong VertexAttribPointer types

---

extensions/NV/NV_pixel_buffer_object.txt

GL_STREAM_READ is not available in ES2.0. In fact, EXT_map_buffer_range
was the first time a mapped buffer could be read from legally.
Just use GL_STREAM_DRAW instead. This  is not a major problem, though,
as the usage hints do not affect the legal usage of a buffer and are
taken by the drivers merely as hints, sometimes even being ignored.
https://github.com/KhronosGroup/OpenGL-API/issues/66

NV_pixel_buffer_object: fix example code

---

extensions/OES/OES_get_program_binary.txt

`glGetProgramBinaryOES` should take the binary size by value, but a pointer was passed in the example code.

Correct example code for OES_get_program_binary

---

xml/gl.xml

this patch adds GL_DEPTH_ATTACHMENT to FramebufferAttachment group in order to allow `glFramebufferRenderbuffer` find right this enum.

fix issue https://github.com/KhronosGroup/OpenGL-API/issues/72

---

xml/gl.xml

This extension was missing from `gl.xml`. It doesn't introduce any new symbols though.

Add EXT_multisampled_render_to_texture2 to gl.xml

---

extensions/EXT/EXT_draw_elements_base_vertex.txt
xml/gl.xml

This is a replacement for https://github.com/KhronosGroup/OpenGL-Registry/pull/414 to also include the extension spec update.

Fix parameter ref for glMultiDrawElementsBaseVertexEXT

---

api/GL/glcorearb.h
api/GL/glext.h
api/GL/glxext.h
api/GL/wgl.h
api/GL/wglext.h
api/GLES/egl.h
api/GLES/gl.h
api/GLES/glext.h
api/GLES/glplatform.h
api/GLES2/gl2.h
api/GLES2/gl2ext.h
api/GLES2/gl2platform.h
api/GLES3/gl3.h
api/GLES3/gl31.h
api/GLES3/gl32.h
api/GLES3/gl3platform.h
api/GLSC2/gl2platform.h
api/GLSC2/glsc2.h
api/GLSC2/glsc2ext.h
xml/Makefile
xml/genglvnd.py
xml/genheaders.py
xml/gl.xml
xml/glx.xml
xml/reg.py
xml/registry.rnc
xml/wgl.xml

text in files. Also implements one recent tweak to the XML into
the generated headers. Otherwise a no-op.
@pdaniell-nv recommend approving ASAP. This has benefits downstream when doing REUSE license checking in repositories which host these files.

Use SPDX License Identifiers instead of including the full Apache / MIT license

---

extensions/NV/NV_memory_object_sparse.txt
xml/gl.xml

This fixes the duplicate "offset" parameter name in the functions:
glBufferPageCommitmentMemNV
glNamedBufferPageCommitmentMemNV
Fixes issue 421

Fix duplicate parameter names in GL_NV_memory_object_sparse

---

extensions/ARB/ARB_gl_spirv.txt

Interal API Issue 132
SPIR-V Issue 254
Previously these were in the SPIR-V universal validation rules.

Add SPIR-V env validation rule for Atomics

---

xml/gl.xml

Length for parameters which use a pointer as an ouptut parameter should have a length of 1 specified. For the fixes here some vendor counterparts do have the length while others don't.
Length for glListDrawCommandsStatesClientNV parameters was not specified despite it being described in the extension spec:
https://www.khronos.org/registry/OpenGL/extensions/NV/NV_command_list.txt
> The <indirects> pointer should point to a list of size <count> of pointers, each of which should point to a command sequence. 
The other parameters can be seen to be used with the same length in description of the DrawCommandsStatesNV function.

Fix inconsistent length out and length for NV_command_list

---

extensions/EXT/GLX_EXT_get_drawable_type.txt
extensions/glext.php
extensions/registry.py

While writing some other client library bits, I discovered a case where I wanted to differentiate based on the type of the GLXDrawable, but that there's no query for that. It was trivial to add, so I added it. This extension formalizes it. I picked EXT because this seems uncontroversial and easy to support, but I'm happy to change it to MESA or XORG or RHT or whatever if there's no other interest.

glx: Add GLX_EXT_get_drawable_type

---

xml/gl.xml

There where a few functions that had `<param>`s there where missing a `len` attribute while the functions ARB counterpart had them.
This PR fixes these inconsistencies.
`glGetnMapdv` and `glGetnPixelMapfv` and their ARB counterparts where also modified to use `COMPSIZE` as their length depends on the pointer element size as well.

Fix param len attribute on multiple functions to match their ARB counterparts

---

xml/gl.xml

Small update to #428.
When updating my bindings to use classes i noticed - i missed few functions returning `GLsync` type...
For most other classes return type is `GLuint`, so i wasn't checking functions by return type.

[xml] Missing class=sync

---

xml/gl.xml

The glProgramUniformMatrix4fvEXT entry point was listed in a second
require block that listed the entry point as depending on GLES 3.0
or GL_NV_non_square_matrices.
Fixes #443
@pdaniell-nv  PTAL

xml: Remove duplicate EP for separate shader ext.

---

extensions/NV/NV_primitive_shading_rate.txt
extensions/esext.php
extensions/glext.php
extensions/registry.py
xml/gl.xml

This extension builds on top of the NV_shading_rate_image extension to
provide OpenGL API support for using a per-primitive shading rate
value to control the computation of the rate used to process each
fragment.
--
I think I have prepared this pull request successfully.  I did build headers and other materials, but my understanding is that I'm supposed to leave this out of a pull request and that those generated files will be rebuilt at the time the extensions are merged and/or published.  Let me know if there are any issues with this submission.
Thanks,
Pat
@pdaniell-nv

Add NV_primitive_shading_rate extension.

---

xml/gl.xml

```c
glGetnUniformdv
glGetnUniformuiv
glGetPerfMonitorCounterData
glGetnMapdv
glGetnPixelMapfv
```
All have a parameter with a length attribute for a parameter which is not of type `void*` or `const void*`. The length is specified in byte count which makes its length attribute incorrect as its written like if it was an element count.

Update len attributes

---

extensions/ARB/ARB_indirect_parameters.txt

Fixes issue https://github.com/KhronosGroup/OpenGL-API/issues/77.
The "maxdrawcount" parameter type wasn't self-consistent within the ARB_indirect_parameters extension specification. It should be the same "sizei" type everywhere in the spec.

Update maxdrawcount parameter type in ARB_indirect_parameters to be consistent

---

extensions/EXT/EXT_disjoint_timer_query.txt

This fixes incomplete code in example (2) and wrong parameter order of `glQueryCounterEXT` in example (3)

Fix code sample in EXT_disjoint_timer_query

---

xml/gl.xml

`glShaderBinary` had no supported enums from v4.1 to 4.5 as `GL_SHADER_BINARY_FORMAT_SPIR_V` was only added in 4.6
According to the documentation however it seems like GL_SHADER_BINARY_FORMATS is also a supported enum. Unless i misunderstood something, in which case i will hapily change this.

GL_SHADER_BINARY_FORMATS included in shader binary format

---

README.adoc

It's about time we start working to get #335 closed off. After a number of checkups in that thread, it seems that most users are happy for the old-style groupings to be removed, either having migrated to the new-style attributes or are in the process of doing so (maintaining a fork in the meantime)
The old-style groups have been deprecated for a long time now, so I've proposed a 3 month timeline between the date of merge and removal. The notice I have added to the README is akin to the one that was added to Vulkan a little while back.
I've enabled "Allow edits by maintainers" so the merger of this PR will be able to fill in the missing dates annotated with `XX` by just editing the file on the PR.

Advance notice of old-style grouping removals

---

extensions/SGI/GLX_SGI_video_sync.txt

This is somewhat trivial since it just says the behavior is undefined,
but implementations do diverge in the wild so better to put up some
caution tape.

GLX_SGI_video_sync: Note the interaction with ARB_framebuffer_object

---

xml/gl.xml

This PR adds a new enum group `SizedInternalFormat` that is used to more specifically group the enums that are valid in calls to functions such as `glTexStorage2D` etc.
I could find documentation for most of the functions and enums, but `EXT_texture_compression_latc` doesn't specify if it can be passed to functions like `glTexStorage2D` or not, so I decided to not add the `SizedInternalFormat` group to those.
```
GL_COMPRESSED_LUMINANCE_LATC1_EXT
GL_COMPRESSED_SIGNED_LUMINANCE_LATC1_EXT
GL_COMPRESSED_LUMINANCE_ALPHA_LATC2_EXT
GL_COMPRESSED_SIGNED_LUMINANCE_ALPHA_LATC2_EXT
```
I also added the `InternalFormat` group to a few enums and commands where they where missing. (e.g. `glMultiTexBufferEXT`)

Added SizedInternalFormat enum group for functions that need explicitly sized formats

---

xml/gl.xml

These functions were previously listed only in NV_vertex_program4, but
are described in both extension specifications. The NV_vertex_program4
extension explicitly states that they are shared with EXT_gpu_shader4,
so the xml should reflect this.
Fixes https://github.com/KhronosGroup/OpenGL-Registry/issues/463

Add missing glVertexAttribI* functions in EXT_gpu_shader4

---

extensions/NV/NV_shader_atomic_int64.txt

Rename the GLASM option `NV_shader_atomic_uint64` to `NV_shader_atomic_int64` (remove the 'u' in 'uint64').
The implementation of this extension checks for `NV_shader_atomic_int64` and signals `uint64` as invalid. The extension itself is named without the 'u', and applications relying on this would break if the driver is changed, so I assume it's a typo.
I think changing the spec to match the current behavior is the path with less friction. I considered opening an issue about this, but opted to open this pull request given the simplicity of the change. Let me know if I missed something so it can be amended.
If the approach here is wrong, please close this pull request.

Remove 'u' from NV_shader_atomic_uint64 GLASM option

---

extensions/MESA/MESA_bgra.txt
extensions/registry.py
xml/gl.xml

This extensions adds the pairs BGRA_EXT/RGBA8 and BGR_EXT/RGB8
to the accepted combinations for format/internalformat in the
TexImage and TexSubImage calls. This is of interest in virtualized
enviornments where one wants to emulate a subset of OpenGL in a guest
that runs on a host that supports only GLES.
An implementation is currently about to be merged in mesa: 
https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/10613

 Add the MESA_bgra GLES extension

---

xml/gl.xml

I noticed some methods with char*'s didnt have len attributes. This pr fixes almost all of them.
https://www.khronos.org/registry/OpenGL/extensions/QCOM/QCOM_extended_get2.txt
glExtGetProgramBinarySourceQCOM is missing a len attribute for parameter 'source'
Didn't find a direct message in the documentation. But based on the parameter names, I would say this is fixed correctly.
https://www.khronos.org/registry/OpenGL/extensions/NV/NV_transform_feedback.txt
glGetActiveVaryingNV has a 'COMPSIZE' string length for parameter 'name'!
`The actual number of characters written into <name>, excluding
the null terminator, is returned in <length>` Hence this should not be a compsize, but rather just point to the length parameter.
https://www.khronos.org/registry/OpenGL/extensions/ANGLE/ANGLE_translate …

Add len parameters to char* methods

---

xml/gl.xml

The idea with this PR is to fix an inconsistency where most `<enum>` tags within an `<enums>` tag with a `group` attribute also contain a `group` attribute with the same group.
Eg.
```xml
<enums namespace="GL" group="AttribMask" type="bitmask">
<enum value="0x00000001" name="GL_CURRENT_BIT" group="AttribMask"/>
...
```
The group `"AttribMask"` is annotated both on the `enums` tag as well as the individual `enum` tags.
But there are 5 enum groups where this isn't the case.
```
group="RegisterCombinerPname"
group="PathRenderingMaskNV"
group="PathRenderingTokenNV"
group="SpecialNumbers"
group="ContainerType"
```
What this PR does currently:
There are two interesting questions relating to the remaining groups:
First, both `"PathRenderingMaskNV"` and `"PathRenderingTokenNV"` are defined on …

Distribute group attribute from <enums> tags to individual <enum> tags.

---

xml/gl.xml

Removed `COMPSIZE` from the `len` attributes from the parameters to applicable glMultiDraw* functions.
```c
// https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glMultiDrawArrays.xhtml
glMultiDrawArrays
glMultiDrawArraysEXT
//https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glMultiDrawElements.xhtml
glMultiDrawElements
glMultiDrawElementsEXT
// https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glMultiDrawElementsBaseVertex.xhtml
glMultiDrawElementsBaseVertex
glMultiDrawElementsBaseVertexEXT
// https://www.ibm.com/docs/en/aix/7.1?topic=subroutines-glmultimodedrawarraysibm-subroutine
glMultiModeDrawArraysIBM
// https://www.ibm.com/docs/en/aix/7.1?topic=subroutines-glmultimodedrawelementsibm-subroutine
glMultiModeDrawElementsIBM
```
I also added COMPSIZE to three …

Removed unnecessary COMPSIZE for all glMultiDraw* functions

---

extensions/EXT/EXT_external_objects.txt

Just a couple of fixes to simple typos in `EXT_external_objects`

Fixing some typos in EXT_external_objects

---

xml/gl.xml

Some minor fixes in gl.xml:
The parameter `target` of the `glGetInternalformati*` functions belongs to the `TextureTarget` group. Since `GL_RENDERBUFFER` is a valid value for `target` in those functions, it needs to be added to the `TextureTarget` group.
* `GL_FETCH_PER_SAMPLE_ARM` (`EnableCap`, `GetPName`)
* `GL_FRAGMENT_SHADER_FRAMEBUFFER_FETCH_MRT_ARM` (`GetPName`)
The group of `format` in the `glCompressed*TexSubImage*` functions was set to `PixelFormat`. However, the correct group seems to be `InternalFormat`, which is containing the valid values for that parameter.

Glxml fixes

---

xml/gl.xml

Fixes #498 
I haven't included the regenerated headers in this. Let me know if I should.

Change int to GLint for attrib_list parameters in TexStorageAttribs2DEXT and TexStorageAttribs3DEXT.

---

api/GLES2/gl2ext.h
extensions/EXT/EXT_separate_depth_stencil.txt
extensions/registry.py
xml/gl.xml

Allows separate depth and stencil buffers to be attached to an FBO in GLES3.

Add EXT_separate_depth_stencil extension

---

xml/gl.xml

This was inserted in #343, probably as an accidental side-effect of
someone's editor - it is not mentioned in the PR comments - and is
breaking downstream scripts in vk-gl-cts which consume the file. The file encoding is defined to be UTF-8 in any event.

Remove BOM from gl.xml

---

extensions/EXT/EXT_shader_samples_identical.txt
extensions/esext.php
extensions/registry.py

It looks like https://github.com/KhronosGroup/OpenGL-Registry/pull/504 didn't update registry.py - and then there was a race with GL_EXT_separate_depth_stencil resulting in both taking ES extension number 338.
GL_EXT_separate_depth_stencil  is now not visible from https://www.khronos.org/registry/OpenGL/index_es.php.
This resolves the numbering conflict in favor of GL_EXT_separate_depth_stencil just because that was merged first.
CC: @jekstrand, @oddhack

Fix ES extension numbering conflict between GL_EXT_shader_samples_identical and GL_EXT_separate_depth_stencil

---

xml/gl.xml

Found this small typo while cleaning up data scrappers.

Typo: TexStorageAttribs__s__

---

api/GL/glext.h
api/GL/glxext.h
api/GL/wgl.h
api/GL/wglext.h
api/GLES/gl.h
api/GLES/glext.h
api/GLES2/gl2.h
api/GLES2/gl2ext.h
api/GLES3/gl3.h
extensions/EXT/EXT_fragment_shading_rate.txt
extensions/esext.php
extensions/glext.php
extensions/registry.py
xml/gl.xml

This extensions adds support for fragment shading rates larger than 1x1 to OpenGL ES, closely matching the support exposed via VK_KHR_fragment_shading_rate in Vulkan.
CC: @pdaniell-nv

Add GL_EXT_fragment_shading_rate

---

api/GLSC2/glsc2ext.h
extensions/IMG/IMG_tile_region_protection.txt
extensions/registry.py
extensions/scext.php
index_sc.php
xml/gl.xml

This extension for OpenGL SC2.0 allows applications to tag all its
safety-critical geometric primitives as safety-related in order to run
safety integrity checks on them when rendering them on
Imagination Technologies safety-critical Tile Based rendering GPUs.

Add IMG_tile_region_protection extension for GLSC 2.0

---

xml/Makefile

glsc2 headers were missed out from the GLHEADERS in the makefile and as
a result they were not generated.
Fix: Added glsc2 headers to the makefile.

Add glsc2 headers to makefile for generation

---

extensions/EXT/EXT_external_objects.txt
extensions/EXT/EXT_external_objects_fd.txt
extensions/EXT/EXT_external_objects_win32.txt

-SignalSemaphoreEXT implicitly flushes command stream
-None of the new external object commands can be included in display lists

Add implicit flush and non-listable commands to external objects

---

xml/gl.xml

The GL_ATI_fragment_shader extension had 4 of its enum groups defined, 3 of them never used.
I was fixing them as part of #520. But then I noticed how much more is missing and decided to add the rest of the groups.
I know this extension is outdated, but I don't want to leave it still half-baked after my changes.
From the [spec](https://github.com/KhronosGroup/OpenGL-Registry/blob/main/extensions/ATI/ATI_fragment_shader.txt), here are lists of which function takes what enums:
```
dst: REG_0_ATI
=	dstMod: NONE, 2X_BIT_ATI, 4X_BIT_ATI, 8X_BIT_ATI, HALF_BIT_ATI, QUARTER_BIT_ATI, EIGHTH_BIT_ATI, SATURATE_BIT_ATI
=	dstMask: NONE, RED_BIT_ATI, GREEN_BIT_ATI, BLUE_BIT_ATI
argN: REG_0_ATI, CON_0_ATI, ZERO, ONE, PRIMARY_COLOR_ARB, SECONDARY_INTERPOLATOR_ATI
argNRep: NONE, RED, GREEN, BLUE, ALPHA
= …
```

[xml] Group fixes for GL_ATI_fragment_shader

---

xml/gl.xml

Add missing "len=" attribs to about ten XML core API command definitions
Correct one "len=" attrib from unnecessary COMPSIZE to size in bytes
Found these while trying to autogenerate a Python API for the Core OpenGL 4.6 commands directly from the XML

Add missing len attributes to GL commands

---

xml/wgl.xml

See issue #525 
After this change my loader generates identical declarations to wingdi.h
Reference
DescribePixelFormat https://docs.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-describepixelformat
wglDescribeLayerPlane https://docs.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-wgldescribelayerplane
GetEnhMetaFilePixelFormat https://docs.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-getenhmetafilepixelformat
wglGetLayerPaletteEntries https://docs.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-wglgetlayerpaletteentries

Update core WGL function signatures to match wingdi.h

---

extensions/EXT/EXT_shader_pixel_local_storage.txt
extensions/EXT/EXT_shader_pixel_local_storage2.txt

Clarify that PLS doesn't allow leak from outside framebuffer

---

xml/gl.xml

This includes a few GLES 1.x enumes and a few others that we use
in ANGLE.
See http://anglebug.com/6461 for context.
@pdaniell-nv @oddhack PTAL

Add enum groups for ANGLE use cases.

---

extensions/EXT/EXT_separate_depth_stencil.txt

Adds explicit mention of the conditions that may cause implementations
to return FRAMEBUFFER_UNSUPPORTED for framebuffers with separate depth
and stencil. (The spec currently allows implementations to return
FRAMEBUFFER_UNSUPPORTED for any implementation dependent reason, so this
is not a spec change, but it is more helpful for users of the API if
these conditions are set out in the spec.)

EXT_separate_depth_stencil: Explicit unsupported cases

---

xml/gl.xml

Fixes #500 
Adds the `PixelType` group to the following enums
```c
GL_HALF_FLOAT
GL_HALF_FLOAT_ARB
GL_HALF_FLOAT_NV
GL_HALF_APPLE
GL_UNSIGNED_INT_24_8
GL_UNSIGNED_INT_24_8_EXT
GL_UNSIGNED_INT_24_8_NV
GL_UNSIGNED_INT_24_8_OES
GL_UNSIGNED_INT_10F_11F_11F_REV
GL_UNSIGNED_INT_10F_11F_11F_REV_APPLE
GL_UNSIGNED_INT_10F_11F_11F_REV_EXT
GL_UNSIGNED_INT_5_9_9_9_REV
GL_UNSIGNED_INT_5_9_9_9_REV_APPLE
GL_UNSIGNED_INT_5_9_9_9_REV_EXT
GL_FLOAT_32_UNSIGNED_INT_24_8_REV
GL_FLOAT_32_UNSIGNED_INT_24_8_REV_NV
```

Added group PixelType to multiple-enums

---

xml/gl.xml

Maybe we should also touch [this](https://github.com/KhronosGroup/OpenGL-Registry/blob/eae1d6dde1e283f6fdf803274a2484007e592599/extensions/EXT/EXT_separate_shader_objects.gles.txt) since related function got changed?

[XML] Made `glCreateShaderProgramvEXT` same as `glCreateShaderProgramv`

---

xml/gl.xml

Ensure that the DrawElements* commands use the proper DrawElementsType
group for type params. Some of these were set to PrimitiveType

[xml] Fix param group in DrawElements* commands

---

extensions/EXT/WGL_EXT_create_context_es2_profile.txt

Version 4 in the Revision History section already said "Add support for any OpenGL-ES version, not just version 2.0", which makes the use of "support and requested version of OpenGL-ES" in issue 5 an unambiguous typo.
I assume this doesn't need an additional entry in the history section, as similar typo fixes were made in e.g. d62c37dde0a40148aecc9e9701ba0ae4ab83ee22.

Fix typo in WGL_EXT_create_context_es2_profile

---

extensions/KHR/KHR_texture_compression_astc_hdr.txt

Integer Sequence Encoding is section C.2.12, not C.3.12

Fix incorrect section number

---

xml/gl.xml

These were added in #546. Only noticed now, because it doesn't affect anything.

[XML] Remove `TextureEnvParameter` enum group dup

---

xml/gl.xml

This extension is already in extensions/, but was missing from the XML. Add the three tokens it defines and re-generate the API.
Closes https://github.com/KhronosGroup/OpenGL-Registry/issues/558

Add NV_pack_subimage XML

---

xml/gl.xml
xml/readme.tex
xml/registry.rnc

Fixes #517 
I've used the word `kind` here to indicate that the label indicates the kind if value the parameter is (eg `ClampedFloat32` or `CoordF`). 
I was thinking about other words to use such as "attrib", "category", "variety", "set" or "label", but personally it seemed like "kind" was the best, most descriptive name.
@Perksey @SunSerega comments?

Rename group attribute for non GLenum parameters not corresponding to any enum group

---

api/GLSC2/glsc2ext.h
extensions/IMG/IMG_pvric_end_to_end_signature.txt
extensions/registry.py
extensions/scext.php
xml/gl.xml

This extension for OpenGL SC 2.0 provides a safety signature mechanism for Imagination Technologies PowerVR Image Compression (PVRIC), that can be used to verify the integrity of the
compression and decompression done by PVRIC as well as the corresponding memory accesses data paths, when processing safety-related workloads, in the presence of potential faults.

Add IMG_pvric_end_to_end_signature extension for GLSC 2.0

---

xml/glx.xml

Adds the missing `XID` type for the X headers as a placeholder type, in the same manner other types from X such as `Display` are. In addition, the comment is updated to make it clearer.
See: https://github.com/KhronosGroup/OpenGL-Registry/issues/572

Update glx.xml to include the XID type.

---

xml/gl.xml

This enum block is not referenced by any interface definitions (which makes since gl.xml doesn't really concern itself with WebGL) but it might still be useful to add these missing enums for the sake of posterity.
- `GL_UNMASKED_VENDOR_WEBGL` and `GL_UNMASKED_RENDERER_WEBGL` from [WEBGL_debug_renderer_info](https://registry.khronos.org/webgl/extensions/WEBGL_debug_renderer_info/)
- `GL_MAX_CLIENT_WAIT_TIMEOUT_WEBGL` from the [WebGL 2.0 Specification](https://registry.khronos.org/webgl/specs/latest/2.0/)
- `GL_TEXTURE_VIDEO_IMAGE_WEBGL` and `GL_SAMPLER_VIDEO_IMAGE_WEBGL` from [WEBGL_video_texture](https://registry.khronos.org/webgl/extensions/proposals/WEBGL_video_texture/)
- This extension is still in the "Proposed" state but https://github.com/KhronosGroup/WebGL/pull/2956 suggests they …

[XML] Add missing WebGL enums

---

xml/gl.xml

Looks like the mentioned enumerants were "lost" from the "LightParameter" group in the commit 8794952a2dfe6332e269191b1288995059df30fd. Here is how the "LightParameter" group looked like just before the changes:
```
<group name="LightParameter" comment="Deprecated, use the group attributes instead.">
<enum name="GL_AMBIENT"/>
<enum name="GL_CONSTANT_ATTENUATION"/>
<enum name="GL_DIFFUSE"/>
<enum name="GL_LINEAR_ATTENUATION"/>
<enum name="GL_POSITION"/>
<enum name="GL_QUADRATIC_ATTENUATION"/>
<enum name="GL_SPECULAR"/>
<enum name="GL_SPOT_CUTOFF"/>
<enum name="GL_SPOT_DIRECTION"/>
<enum name="GL_SPOT_EXPONENT"/>
</group>
```
Re-adding the missing enumerants.
Related PR: https://github.com/KhronosGroup/OpenGL-Registry/pull/579

Added GL_AMBIENT, GL_DIFFUSE and GL_SPECULAR enumerants to LightParameter group

---

extensions/QCOM/QCOM_render_shared_exponent.txt

Update GL_QCOM_render_shared_exponent to remove
explicit RGB9_E5 error for copyTex[Sub]Image calls.

Clarify copyTex[Sub]Image for GL_QCOM_render_shared_exponent

---

extensions/EXT/EXT_external_objects_win32.txt

For certain external handle types representing
objects from non-Khronos APIs, it's difficult or
impossible for an application to know the actual
size of the associated memory object. The Vulkan
external memory specifications acknowledge this
in section 11.2.3. "Device Memory Allocation,"
with this language:
"If the parameters define an import operation and
the external handle type is
VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D11_TEXTURE_BIT,
VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D11_TEXTURE_KMT_BIT, or
VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D12_RESOURCE_BIT, allocationSize is ignored. The implementation must query the size of these allocations from the OS."
But the OpenGL external object specs lacked
equivalent language. This change adds such
language.
Additionally, while investigating this spec issue …

Document memory object <size> parameter requirements

---

extensions/ARB/ARB_shader_viewport_layer_array.txt
extensions/OES/OES_viewport_array.txt

gitlab/opengl/api/issue/44
clarify that out-of-range values for gl_Layer and gl_ViewportIndex are undefined

update ARB_shader_viewport_layer_array and OES_viewport_array

---

extensions/QCOM/QCOM_texture_lod_bias.txt

This extension reintroduces LOD bias
as an API state concept. It is based
off the existing 1.1 extension
EXT_texture_lod_bias.

Add QCOM_texture_lod_bias

---

extensions/QCOM/QCOM_render_sRGB_R8_RG8.txt

This allows rendering directly
to sRGB version of R8 and RG8.

Add QCOM_render_sRGB_R8_RG8

---

xml/gl.xml

This PR fixes the `TextureWrapMode` to contain only enums that are texture wrap modes.
This means removing the `TextureWrapMode` group from `GL_LINEAR_MIPMAP_LINEAR`, and adding the group to a few extension defined enums.

Fix TextureWrapMode enum group

---

xml/gl.xml
xml/vendors.txt

Request a block of enums for Samsung.
Private enums for ANGLE use.

Allocate enums for Samsung

---

xml/gl.xml

This updates vendor name from "Qualcomm" to "QCOM" and fix group for new enums 0x9710 and 0x9711.

Update vendor to "QCOM" and fix group for new enums

---

extensions/QCOM/QCOM_ycbcr_degamma.txt
extensions/esext.php
extensions/registry.py
xml/gl.xml

This allows sRGB degamma operation on Y and CbCr
planes of a YCbCr buffer.

Adds QCOM_ycbcr_degamma extension

---

extensions/EXT/EXT_texture_norm16.txt

Internal issue [194](https://gitlab.khronos.org/opengl/API/-/issues/194).

Clarify EXT_texture_norm16 read combinations

---

extensions/EXT/EXT_fragment_shading_rate.txt

For GL_EXT_fragment_shading_rate, someone asked me if all the state in Implementation Dependent Values was gated on support for attachment shading rates (GL_EXT_fragment_shading_rate_attachment). That's not the intent, but the state table can definitely be read that way. (This was probably an 'accident' of us adding more state during the spec process.)
I've tried to clarify this by moving some lines around - where the only actual change is that the "[[If GL_EXT_fragment_shading_rate_attachment is supported]]" statement is now in the middle of table.

GL_EXT_fragment_shading_rate: clarify state table

---

xml/genglvnd.py
xml/genheaders.py

Closes: https://github.com/KhronosGroup/OpenGL-Registry/issues/617
* * *
- Should we use a different symbol name, in case users include both `glext.h` and `gl2ext.h` from different releases?
- Should I re-generate the headers, or should I leave that to the person in charge of the next release?

Add version define to gl2ext.h

---

extensions/EXT/EXT_texture_shadow_lod.txt

One issue referred to a bug that has now been fixed, so is no longer relevant, so this text is removed.
An additional issue is added describing which stages the bias variants are added to. The normative text was already correct but this may aid clarity.
Fixes internal issues 75 and 77. @lexaknyazev

Update issue text for EXT_texture_shadow_lod

---

extensions/EXT/EXT_YUV_target.txt

@lexaknyazev @oddhack Please review / signoff / merge.

fix type casing in GL_EXT_YUV_target

---

xml/gl.xml

NV_texture_barrier is OpenGL ES Extension #271. Let the XML know about that, so it gets added to the appropriate extension headers.

Expose NV_texture_barrier on GLES2

---

api/GL/glext.h
api/GL/glxext.h
api/GL/wgl.h
api/GL/wglext.h
api/GLES/gl.h
api/GLES/glext.h
api/GLES2/gl2.h
api/GLES2/gl2ext.h
api/GLES3/gl3.h
api/GLSC2/glsc2.h
api/GLSC2/glsc2ext.h
extensions/MESA/MESA_texture_const_bandwidth.txt
extensions/esext.php
extensions/glext.php
extensions/registry.py
xml/gl.xml

GL_MESA_texture_const_bandwidth adds a way for an app to request the use of a format which does have data dependent bandwidth characteristics, in order to avoid a potential side-channel.

Add GL_MESA_texture_const_bandwidth

---

extensions/ARB/ARB_shader_texture_image_samples.txt

It is not possible to have more than one texture per binding.
Fixes GitLab GLSL issue 80.

Remove plural bindings in GL_ARB_shader_texture_image_samples

---

extensions/EXT/EXT_shader_clock.txt
extensions/esext.php

Discussed in issue here: https://github.com/KhronosGroup/OpenGL-Registry/issues/647

Add GL_EXT_shader_clock for OpenGL ES (From ARB_shader_clock)

---

extensions/ARB/ARB_direct_state_access.txt

These two typos presumably came from someone copying/pasting other entries and then forgetting to change the text.

Fix interactions naming the wrong extension in ARB_direct_state_access

---

xml/gl.xml

`glNamedBufferData` and `glNamedBufferDataEXT` had their `usage` parameter marked with the `VertexBufferObjectUsage` group, but `BufferUsageARB` is a much better group to use as these functions are not limited to vertex buffers.
And as this was the only use of the `VertexBufferObjectUsage` group, I also remove that group as part of this PR.

Remove VertexBufferObjectUsage in favor of BufferUsageARB

---

api/GL/glcorearb.h
api/GL/glext.h
api/GL/glxext.h
api/GL/wgl.h
api/GL/wglext.h
api/GLES/gl.h
api/GLES/glext.h
api/GLES2/gl2.h
api/GLES2/gl2ext.h
api/GLES3/gl3.h
api/GLSC2/glsc2.h
api/GLSC2/glsc2ext.h
extensions/HUAWEI/HUAWEI_program_binary.txt
extensions/HUAWEI/HUAWEI_shader_binary.txt
extensions/esext.php
extensions/registry.py
xml/gl.xml

`HUAWEI_shader_binary` and `HUAWEI_program_binary` are added to load binary format shaders for devices with HUAWEI GPUs.

Add vendor extensions HUAWEI_shader_binary and HUAWEI_program_binary
